### ISSUE TITLE
Thumbnail view does not work in macOS Mojave

### ISSUE THREAD

**Issue by BinaryHammer** [inloop/qlplayground#1]

**Comment by BinaryHammer** [comment]
It only works when the Icons have a resolution of 100x100 in Icon View. If I change the size of the icons in Icon View to like 96x96 it does not work, even when using $ qlmanage -r. And for example in the gallery view it shows at the bottom just a white empty rectangle.

**Comment by jakubpetrik** [comment]
Thanks for the report. I will look into it.

**Comment by BinaryHammer** [comment]
I deleted every other QuickLook plugin and restarted. Your plugin works now. Maybe some other plugin was  interfering with yours.
